name: Hugo

env:
  AWS_REGION : eu-central-1

permissions:
  id-token: write   # Allow assume IAM Role via GitHub OIDC
  contents: read    # This is required for actions/checkout@v2

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy-dev:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.92.0
          extended: true

      - name: Patch base URL in dev config
        run: |
          sed -i "/baseURL:/s/mauermann.io/${{ secrets.DEV_DOMAIN }}/" config.yml

      - run: hugo --minify

      - name: Configure AWS credentials for dev account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DEV_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy dev website
        run: |
          aws s3 sync public/ s3://${{ secrets.DEV_DOMAIN }}/ --delete

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.92.0
          extended: true

      - run: hugo --minify

      - name: Configure AWS credentials for prod account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PROD_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy prod website
        run: |
          aws s3 sync public/ s3://${{ secrets.PROD_DOMAIN }}/ --delete
